#配置常量
thisProject:
  name: spring_boot_demo
  vision: 5
teacher:
  name: mayoumi
  subject: music

#Spring-Boot编码格式
banner:
  charset: UTF-8

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  messages:
    encoding: UTF-8
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/adc_spring?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #连接池补充设置，初始化大小
    initial-size: 2
    min-idle: 2
    max-idle: 10
    #获得链接等待超时的时间
    max-wait: 80000
    #检测需要关闭的控线连接的间隔时间
    time-between-eviction-runs-millis: 100000
    #配置连接池的最小生存时间
    min-evictable-idle-time-millis: 40000
  #mongoDB配置
  data:
    mongodb:
      uri: mongodb://user1:user1@127.0.0.1:27017/database?authSource=testdb
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 8000
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  #kafka配置
  application:
    name: bd-job-executor-springboot
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      #用于表示此使用者所属组的唯一字符串
      group-id: executor
      # 密钥的反序列化器类
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      group-id: executor
      #key的序列化类
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      #值的序列化类
      valued-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 多个记录被发送到同一分区，生产者记录批量处理数量，默认值为16384
      batch-size: 16384
      #生产者用于缓冲等待发送到服务器的记录内存总字节数，默认33554432
      buffer-memory: 33554432

  #邮件发送JavaMailSender
  mail:
    host: smtp.qq.com
    username: 1419268805@qq.com
    password: bwskiqditefbiihg
    default-encoding: UTF-8
    properties:
      smtp.auth: true
      smtp.starttls.enable: true
      smtp.starttls.required: true

#mybatis配置
mybatis:
  type-aliases-package: com.ke.lisijia.spring_boot_demo.model
  mapper-locations: classpath:mappers/*.xml
  configuration:
    #自动驼峰命名转换
    map-underscore-to-camel-case: true
    #控制台打印SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志配置
logging:
  level:
    root: INFO
  path: /log

#Eureka配置
eureka:
  instance:
    hostname: localhost
  client:
    #禁用服务注册中心将自身作为客户端尝试注册自己
    register-with-eureka: false
    fetch-registry: false
