spring:
  application:
    name: api-gateway
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

zuul:
  routes:
    eureka-consumer-ribbon: /ribbon/**