spring:
  application:
    name: eureka-consumer-ribbon
  cloud:
    stream:
      bindings:
        #输入通道主题名
        Consumer-message:
          #消费组
          group: consumer-A

server:
  port: 2101

eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8080/eureka/


