spring:
  application:
    name: eureka-consumer-ribbon
  cloud:
    stream:
      bindings:
        #输入通道
        input:
          #消费组
          group: consumer-A
          #topic
          destination: Consumer-message

server:
  port: 2101

eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8080/eureka/


